// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227142649_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkF9EKe7KJxAijZ374He4edBGTSujLGRA48MkMwN9g6PK77IM2H..",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "claims@gmail.com",
                            FullName = "Claims Officer",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkF9EKe7KJxAijZ374He4edBGTSujLGRA48MkMwN9g6PK77IM2H..",
                            Role = 4
                        },
                        new
                        {
                            Id = 3,
                            Email = "customer@gmail.com",
                            FullName = "Customer",
                            IsActive = true,
                            PasswordHash = "$2a$11$kkF9EKe7KJxAijZ374He4edBGTSujLGRA48MkMwN9g6PK77IM2H..",
                            Role = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PolicyRequestId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyAge")
                        .HasColumnType("int");

                    b.Property<decimal>("PropertyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyRequestId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimAmount = 5000m,
                            PolicyRequestId = 1,
                            PropertyAddress = "123 Main Street",
                            PropertyAge = 10,
                            PropertyValue = 1000000m,
                            Remarks = "",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ClaimAmount = 15000m,
                            PolicyRequestId = 2,
                            PropertyAddress = "456 Commerce Road",
                            PropertyAge = 5,
                            PropertyValue = 5000000m,
                            Remarks = "",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.PolicyRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgentCommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyAge")
                        .HasColumnType("int");

                    b.Property<decimal?>("PropertyValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RiskScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.ToTable("PolicyRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentCommissionAmount = 0m,
                            CustomerId = 3,
                            PlanId = 1,
                            PremiumAmount = 0m,
                            Status = 6
                        },
                        new
                        {
                            Id = 2,
                            AgentCommissionAmount = 0m,
                            CustomerId = 3,
                            PlanId = 2,
                            PremiumAmount = 0m,
                            Status = 6
                        });
                });

            modelBuilder.Entity("Domain.Entities.PropertyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Property Insurance"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PropertyPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgentCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseCoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoverageRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("PropertyPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgentCommission = 500m,
                            BaseCoverageAmount = 1000000m,
                            BasePremium = 5000m,
                            CoverageRate = 0.02m,
                            PlanName = "Basic Residential Plan",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgentCommission = 1200m,
                            BaseCoverageAmount = 5000000m,
                            BasePremium = 15000m,
                            CoverageRate = 0.03m,
                            PlanName = "Basic Commercial Plan",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgentCommission = 2000m,
                            BaseCoverageAmount = 10000000m,
                            BasePremium = 25000m,
                            CoverageRate = 0.04m,
                            PlanName = "Basic Industrial Plan",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            AgentCommission = 200m,
                            BaseCoverageAmount = 300000m,
                            BasePremium = 2000m,
                            CoverageRate = 0.015m,
                            PlanName = "Basic Contents Plan",
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.PropertySubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PropertySubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "SUB_RES_01",
                            Name = "Residential Property"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "SUB_COM_02",
                            Name = "Commercial Property"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Code = "SUB_IND_03",
                            Name = "Industrial & Special Use"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Code = "SUB_CON_04",
                            Name = "Property Contents"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Claim", b =>
                {
                    b.HasOne("Domain.Entities.PolicyRequest", "PolicyRequest")
                        .WithMany()
                        .HasForeignKey("PolicyRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyRequest");
                });

            modelBuilder.Entity("Domain.Entities.PolicyRequest", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId");

                    b.HasOne("Domain.Entities.ApplicationUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PropertyPlans", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Domain.Entities.PropertyPlans", b =>
                {
                    b.HasOne("Domain.Entities.PropertySubCategory", "SubCategory")
                        .WithMany("Plans")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Domain.Entities.PropertySubCategory", b =>
                {
                    b.HasOne("Domain.Entities.PropertyCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.PropertyCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Domain.Entities.PropertySubCategory", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
